// Dashboard data bundle — generated by bundle-data.sh

export interface DashboardData {
  generated_at: string
  metrics: MetricsEntry[]
  history: History
  nights: Record<string, NightData>
  social: SocialData
  weekly_reports: WeeklyReport[]
  build_repos: string[]
}

// --- Metrics ---

export interface MetricsEntry {
  date: string
  type: 'success' | 'failure'
  scout_duration_s: number
  scout_trends_found?: number
  scout_sources_succeeded?: string[]
  scout_sources_failed?: string[]
  spec_duration_s: number
  spec_decision?: string
  spec_rejection_reason?: string | null
  build_duration_s: number
  build_status?: string
  total_duration_s: number
  project: string | null
  repo_url?: string
  category?: string
  source?: string
  engagement_score?: number
  buildability_score?: number
  cost_usd: number
  tokens_used?: number | null
  notes?: string
}

// --- History ---

export interface History {
  schema_version: number
  builds: HistoryBuild[]
  rejections: HistoryRejection[]
  dedup_window_days: number
}

export interface HistoryBuild {
  date: string
  project_name: string
  title: string
  repo_url: string
  status: string
  source: string
  keywords: string[]
}

export interface HistoryRejection {
  date: string
  title: string
  reason: string
}

// --- Night Data ---

export interface NightData {
  state: PipelineState | null
  spec: SpecOutput | null
  build: BuildOutput | null
  briefing: unknown | null
  engagement: EngagementData | null
  trends_meta: TrendsMeta | null
  trends_top: TrendEntry[]
}

export interface PipelineState {
  schema_version: number
  date?: string
  pipeline_date?: string
  pipeline_status?: string
  start_time?: string
  started_at?: string
  completed_at?: string
  stages: Record<string, StageState>
  current_stage?: string
  briefing_delivered?: boolean
  pipeline_complete?: boolean
  outcome?: string
  summary?: string
  errors?: string[]
}

export interface StageState {
  status: string
  started_at?: string
  completed_at?: string
  compiled_at?: string
  error?: string | null
  decision?: string
  build_status?: string
  type?: string
  sent?: boolean
}

export interface SpecOutput {
  schema_version: number
  decision: string
  date?: string
  spec_date?: string
  selected_trend?: SelectedTrend | null
  selected_trend_id?: string
  selected_trend_title?: string
  reasoning?: string
  rejected_alternatives?: RejectedAlternative[]
  spec?: SpecDetail | null
  meta?: unknown
  next_actions?: unknown
}

export interface SelectedTrend {
  id: string
  title: string
  source?: string
  engagement_score?: number
  buildability_score?: number
}

export interface RejectedAlternative {
  id: string
  title: string
  rejection_reason: string
}

export interface SpecDetail {
  project_name: string
  description: string
  features: string[]
  stack: string[] | Record<string, string>
  scope?: string
  time_estimate?: string
  success_criteria?: string[]
}

export interface BuildOutput {
  schema_version: number
  date: string
  project_name: string
  status: string
  repo_url?: string
  description?: string
  tech_stack?: Record<string, string>
  build?: BuildInfo
  tests?: TestInfo
  metrics?: BuildMetrics
  features_implemented?: string[]
  notes?: string
}

export interface BuildInfo {
  tool: string
  model: string
  duration_seconds: number
  cost: number
  commits?: number
}

export interface TestInfo {
  total?: number
  passed?: number
  failed?: number
  skipped?: number
}

export interface BuildMetrics {
  loc?: number
  files?: number
  dependencies?: number
}

export interface EngagementData {
  date?: string
  checks?: EngagementCheck[]
  [key: string]: unknown
}

export interface EngagementCheck {
  project: string
  stars?: number
  forks?: number
  issues?: number
  score?: number
}

export interface TrendsMeta {
  total_trends: number
  sources_scanned?: string[] | null
  scan_duration_seconds?: number | null
  lifecycle_summary: Record<string, number>
}

export interface TrendEntry {
  id?: string
  title: string
  source?: string
  url?: string
  engagement_score?: number
  buildability_score?: number
  final_score?: number
  lifecycle_status?: string
  keywords?: string[]
}

// --- Social ---

export interface SocialData {
  content_queue: ContentQueue | null
  voice_patterns: VoicePatterns | null
}

export interface ContentQueue {
  schema_version: number
  last_updated: string
  pending: SocialDraft[]
  approved: SocialDraft[]
  rejected: SocialDraft[]
  posted: SocialDraft[]
}

export interface SocialDraft {
  id: string
  created: string
  source_build: string
  content_type: string
  priority: number
  estimated_engagement: string
  status: string
  platforms: {
    x?: PlatformDraft
    reddit?: PlatformDraft
  }
}

export interface PlatformDraft {
  format: string
  tweets?: string[]
  title?: string
  body?: string
  subreddit?: string
}

export interface VoicePatterns {
  schema_version: number
  last_updated: string
  source: string
  patterns: Record<string, unknown>
  nick_corrections: unknown
  engagement_learnings: unknown
}

// --- Weekly Reports ---

export interface WeeklyReport {
  [key: string]: unknown
}
